### ISSUE TITLE
Karapace unable to authenticate against SASL SCRAM.

### ISSUE THREAD

**Issue by tobiasbrodersen** [Aiven-Open/karapace#438]
# What happened?
Karapace is unable to connect to Kafka clusters using SASL SCRAM, caused by lack of `SASL_VERSION 1` support in [kafka-python](https://github.com/dpkp/kafka-python)
This is fixed by https://github.com/aiven/kafka-python/pull/21, but it probably needs more work to be merged into your fork, if anyone is familiar with this client code please reach out.

# What did you expect to happen?

Using below config we expected for Karapace to be able to connect to our clusters:
```
listeners=...,SSLAUTH://:9092
listener.security.protocol.map=...,SSLAUTH:SASL_SSL
sasl.enabled.mechanisms=SCRAM-SHA-512
listener.name.sslauth.scram-sha-512.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required;
```
# What else do we need to know?
KIP: https://cwiki.apache.org/confluence/display/KAFKA/KIP-152+-+Improve+diagnostics+for+SASL+authentication+failures
Implemented from Kafka 1.0.0

**Comment by raphaelauv** [comment]
I don't know if it help but this work 

```yaml
  aiven-rest-proxy:
    image: ghcr.io/aiven/karapace:3.3.1
    entrypoint:
      - /bin/bash
      - /opt/karapace/start.sh
      - rest
    ports:
      - "8082:8082"
    environment:
      KARAPACE_PORT: 8082
      KARAPACE_HOST: 0.0.0.0
      KARAPACE_ADVERTISED_HOSTNAME: aiven-rest-proxy
      KARAPACE_BOOTSTRAP_URI: $AIVEN_BOOTSTRAP_SERVERS
      KARAPACE_SECURITY_PROTOCOL: SASL_SSL
      KARAPACE_SASL_MECHANISM: SCRAM-SHA-256
      KARAPACE_SASL_PLAIN_USERNAME: $AIVEN_SASL_PLAIN_USERNAME
      KARAPACE_SASL_PLAIN_PASSWORD: $AIVEN_SASL_PLAIN_PASSWORD
      KARAPACE_SSL_CAFILE: "/opt/conf/ca.pem"
```
